### ISSUE TITLE
guess = True reads in very unintuitive way

### ISSUE THREAD

**Issue by hamogu** [taldcroft/asciitable#20]
Hi,

I read the following table (this is a minimal example):

```
relpix           1450           1500 
-50     8.0990e-05     8.2770E-05
-49     8.7960e-05     8.9560E-05
```

When I look at that, I expect a get a table with 3 columns and 2 rows and, sure enough, this is what I get from:

```
dat  = asciitable.read('test.dat', guess = False)
rec.array([(-50, 8.0989999999999995e-05, 8.2769999999999995e-05),
   (-49, 8.7960000000000005e-05, 8.9560000000000003e-05)], 
  dtype=[('relpix', '<i8'), ('1450', '<f8'), ('1500', '<f8')])
```

However, without the `guess = False`  I get a table with 3 rows:

```
asciitable.read('test.dat') 
rec.array([('relpix', 1450.0, 1500.0),
   ('-50', 8.0989999999999995e-05, 8.2769999999999995e-05),
   ('-49', 8.7960000000000005e-05, 8.9560000000000003e-05)], 
  dtype=[('col1', '|S6'), ('col2', '<f8'), ('col3', '<f8')])
```

where the first column is a string, because its label is a string. I don't know what the exact reasoning is in the way the guesses are ordered, but it seems to me, that `guess= True` should read this simple table in the same way `guess = False` does.

**Comment by taldcroft** [comment]
Guess won't allow a column name that looks like a number.  Otherwise it would parse the following table as having columns named "1" and "2":

```
1 2
3 4
```

The current behavior is that it will decide this is a headerless table and give auto-generated column names "col1" and "col2".  This is desired since many astronomers will feed in tables of mostly numeric data with no header definition.

It's difficult to define a behavior for guess that will work in every case, in which case you need to help it out with guess=False.  In this case with guess=False you have implicitly given it information that the first line is the header and that the columns are space-delimited so it produced your expected output.

**Comment by taldcroft** [comment]
Will improve docs about how guess works to reduce the chance of surprises.  (In case anybody actually reads the documentation).

**Comment by taldcroft** [comment]
Doc update in 0.7.1.
